name: "Setup SOPS and Age with Cache"
description: "Installs SOPS and Age with caching for speed"

runs:
  using: "composite"
  steps:
    - name: Cache SOPS Binary
      id: cache-sops
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/sops
        key: ${{ runner.os }}-sops-3.8.1

    - name: Install SOPS (if not cached)
      if: steps.cache-sops.outputs.cache-hit != 'true'
      shell: bash
      run: |
        SOPS_VERSION="3.8.1"
        curl -LO https://github.com/getsops/sops/releases/download/v${SOPS_VERSION}/sops-v${SOPS_VERSION}.linux.amd64
        chmod +x sops-v${SOPS_VERSION}.linux.amd64
        sudo mv sops-v${SOPS_VERSION}.linux.amd64 /usr/local/bin/sops

    - name: Cache Age Binary
      id: cache-age
      uses: actions/cache@v4
      with:
        path: /usr/bin/age
        key: ${{ runner.os }}-age-v1

    - name: Install Age (if not cached)
      if: steps.cache-age.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install age -y
