// This file is auto-generated by @hey-api/openapi-ts

export type { ClientOptions, GetCurrentUserData, GetCurrentUserResponse, GetCurrentUserResponses, Role, SendVerificationEmailData, SendVerificationEmailResponses, SignInData, SignInDto, SignInResponse, SignInResponses, SignOutData, SignOutResponse, SignOutResponses, SignUpData, SignUpDto, SignUpResponses, UpdateAccountData, UpdateAccountResponse, UpdateAccountResponses, UpdateUserDto, UserEntity, VerifyEmailData, VerifyEmailResponses } from './types.gen';
