// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type UserEntity = {
    id: number;
    email: string;
    firstName: string;
    lastName: string;
    role: string;
};

export type SignInDto = {
    email: string;
    password: string;
};

export type SignUpDto = {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    confirmPassword: string;
};

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user';
};

export type GetCurrentUserResponses = {
    200: UserEntity;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type SignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type SignInResponses = {
    200: unknown;
};

export type SignUpData = {
    body: SignUpDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type SignUpResponses = {
    201: unknown;
};

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutResponses = {
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];
