// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type SignInDto = {
    email: string;
    password: string;
};

export type SignUpDto = {
    firstName: string;
    lastName: string;
    email: string;
    password: string;
    confirmPassword: string;
};

export type Role = 'admin' | 'user';

export type UserEntity = {
    role: Role;
    id: number;
    email: string;
    firstName: string;
    lastName: string;
};

export type SignInData = {
    body: SignInDto;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type SignInResponses = {
    200: string;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];

export type SignUpData = {
    body: SignUpDto;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type SignUpResponses = {
    201: unknown;
};

export type SignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type SignOutResponses = {
    204: void;
};

export type SignOutResponse = SignOutResponses[keyof SignOutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetCurrentUserResponses = {
    200: UserEntity;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];
