// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zSignInDto = z.object({
    email: z.email(),
    password: z.string()
});

export const zSignUpDto = z.object({
    firstName: z.string().min(2).max(255),
    lastName: z.string().min(2).max(255),
    email: z.email(),
    password: z.string(),
    confirmPassword: z.string()
});

export const zRole = z.enum(['admin', 'user']);

export const zUserEntity = z.object({
    role: zRole,
    id: z.number(),
    email: z.string(),
    firstName: z.string(),
    lastName: z.string()
});

export const zSignInData = z.object({
    body: zSignInDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zSignInResponse = z.string();

export const zSignUpData = z.object({
    body: zSignUpDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zSignOutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zSignOutResponse = z.void();

export const zGetCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetCurrentUserResponse = zUserEntity;
