// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zSignInDto = z.object({
    email: z.email(),
    password: z.string()
});

export const zSignUpDto = z.object({
    firstName: z.string().min(2).max(255),
    lastName: z.string().min(2).max(255),
    email: z.email(),
    password: z.string(),
    confirmPassword: z.string()
});

export const zRole = z.enum(['admin', 'user']);

export const zUserEntity = z.object({
    role: zRole,
    id: z.number(),
    email: z.email(),
    firstName: z.string().min(2).max(255),
    lastName: z.string().min(2).max(255),
    isVerified: z.boolean(),
    isBlocked: z.boolean()
});

export const zUpdateUserDto = z.object({
    firstName: z.optional(z.string().min(2).max(255)),
    lastName: z.optional(z.string().min(2).max(255))
});

export const zSignInData = z.object({
    body: zSignInDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zSignInResponse = z.string();

export const zSignUpData = z.object({
    body: zSignUpDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zUpdateTokenData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zUpdateTokenResponse = z.string();

export const zSignOutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zSignOutResponse = z.void();

export const zGetCurrentUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetCurrentUserResponse = zUserEntity;

export const zSendVerificationEmailData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zVerifyEmailData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetAccountData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetAccountResponse = zUserEntity;

export const zUpdateAccountData = z.object({
    body: zUpdateUserDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zUpdateAccountResponse = zUserEntity;
